<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE manifest [
    <!ELEMENT manifest (module, version, license, description, author+, dependencies?, contents)>
    <!ATTLIST manifest
        version CDATA   #REQUIRED
    >

    <!ELEMENT module (#PCDATA)>

    <!ELEMENT version (release, api, stability)>

    <!ELEMENT stability (release, api)>

    <!ELEMENT release (#PCDATA)>

    <!ELEMENT api (#PCDATA)>

    <!ELEMENT description (#PCDATA)>

    <!ELEMENT author (name, email?, homepage?)>

    <!ELEMENT name (#PCDATA)>
    
    <!ELEMENT email (#PCDATA)>
    
    <!ELEMENT hompeage (#PCDATA)>

    <!ELEMENT dependencies (dependency*)>

    <!ELEMENT dependency EMPTY>
    <!ATTLIST dependency
        module  CDATA   #REQUIRED
        version CDATA   #REQUIRED
    >

    <!ELEMENT contents (directory*, file*)>
    
    <!ELEMENT directory (directory*, file*)>
    <!ATTLIST directory
        name    CDATA   #REQUIRED
    >

    <!ELEMENT file EMPTY>
    <!ATTLIST file
        name    CDATA   #REQUIRED
        md5sum  CDATA   #REQUIRED
    >
]>

<manifest version="1.0">
    <module>Manager</module>

    <version>
        <release>0.1</release>
        <api>0.1</release>

        <stability>
            <release>beta</release>
            <api>beta</api>
        </stability>
    </version>

    <license uri="http://www.fsf.org/licensing/licenses/agpl-3.0.html">Affero GNU General Public License</license>

    <description>Content management module.</description>

    <author>
        <name>meh.</name>
        <email>meh@paranoici.org</email>
        <homepage>http://meh.doesntexist.org</homepage>
    </author>

    <dependencies>
        <dependency module="Security" version=">=0.2"/>
    </dependencies>

    <contents>
    </contents>
</module>
